//
//irpc.proto
//Author: Kunyao Wu
//the definition of data structure and service
//for table transmisison(PushTable)
//and executer call(ExecuterCaller)

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.13.0
// source: irpc.proto

package irpccall

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type IrpcCallReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Txnid int64 `protobuf:"varint,1,opt,name=Txnid,proto3" json:"Txnid,omitempty"`
}

func (x *IrpcCallReq) Reset() {
	*x = IrpcCallReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_irpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IrpcCallReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IrpcCallReq) ProtoMessage() {}

func (x *IrpcCallReq) ProtoReflect() protoreflect.Message {
	mi := &file_irpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IrpcCallReq.ProtoReflect.Descriptor instead.
func (*IrpcCallReq) Descriptor() ([]byte, []int) {
	return file_irpc_proto_rawDescGZIP(), []int{0}
}

func (x *IrpcCallReq) GetTxnid() int64 {
	if x != nil {
		return x.Txnid
	}
	return 0
}

type IrpcStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsSuc int64 `protobuf:"varint,1,opt,name=isSuc,proto3" json:"isSuc,omitempty"`
}

func (x *IrpcStatus) Reset() {
	*x = IrpcStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_irpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IrpcStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IrpcStatus) ProtoMessage() {}

func (x *IrpcStatus) ProtoReflect() protoreflect.Message {
	mi := &file_irpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IrpcStatus.ProtoReflect.Descriptor instead.
func (*IrpcStatus) Descriptor() ([]byte, []int) {
	return file_irpc_proto_rawDescGZIP(), []int{1}
}

func (x *IrpcStatus) GetIsSuc() int64 {
	if x != nil {
		return x.IsSuc
	}
	return 0
}

type Table struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Createstmt string `protobuf:"bytes,1,opt,name=createstmt,proto3" json:"createstmt,omitempty"` //create TableName (Col1 varchar(255), Col2 int, Col3 varchar255)
}

func (x *Table) Reset() {
	*x = Table{}
	if protoimpl.UnsafeEnabled {
		mi := &file_irpc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Table) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Table) ProtoMessage() {}

func (x *Table) ProtoReflect() protoreflect.Message {
	mi := &file_irpc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Table.ProtoReflect.Descriptor instead.
func (*Table) Descriptor() ([]byte, []int) {
	return file_irpc_proto_rawDescGZIP(), []int{2}
}

func (x *Table) GetCreatestmt() string {
	if x != nil {
		return x.Createstmt
	}
	return ""
}

var File_irpc_proto protoreflect.FileDescriptor

var file_irpc_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x69, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x69, 0x72,
	0x70, 0x63, 0x22, 0x23, 0x0a, 0x0b, 0x49, 0x72, 0x70, 0x63, 0x43, 0x61, 0x6c, 0x6c, 0x52, 0x65,
	0x71, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x78, 0x6e, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x05, 0x54, 0x78, 0x6e, 0x69, 0x64, 0x22, 0x22, 0x0a, 0x0a, 0x49, 0x72, 0x70, 0x63, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x73, 0x53, 0x75, 0x63, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x69, 0x73, 0x53, 0x75, 0x63, 0x22, 0x27, 0x0a, 0x05, 0x54,
	0x61, 0x62, 0x6c, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x73, 0x74,
	0x6d, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x73, 0x74, 0x6d, 0x74, 0x32, 0x39, 0x0a, 0x09, 0x50, 0x75, 0x73, 0x68, 0x54, 0x61, 0x62, 0x6c,
	0x65, 0x12, 0x2c, 0x0a, 0x09, 0x50, 0x75, 0x73, 0x68, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x0b,
	0x2e, 0x69, 0x72, 0x70, 0x63, 0x2e, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x1a, 0x10, 0x2e, 0x69, 0x72,
	0x70, 0x63, 0x2e, 0x49, 0x72, 0x70, 0x63, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x00, 0x32,
	0x47, 0x0a, 0x0e, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x72, 0x43, 0x61, 0x6c, 0x6c, 0x65,
	0x72, 0x12, 0x35, 0x0a, 0x0c, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x72, 0x43, 0x61, 0x6c,
	0x6c, 0x12, 0x11, 0x2e, 0x69, 0x72, 0x70, 0x63, 0x2e, 0x49, 0x72, 0x70, 0x63, 0x43, 0x61, 0x6c,
	0x6c, 0x52, 0x65, 0x71, 0x1a, 0x10, 0x2e, 0x69, 0x72, 0x70, 0x63, 0x2e, 0x49, 0x72, 0x70, 0x63,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x00, 0x42, 0x0a, 0x5a, 0x08, 0x69, 0x72, 0x70, 0x63,
	0x63, 0x61, 0x6c, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_irpc_proto_rawDescOnce sync.Once
	file_irpc_proto_rawDescData = file_irpc_proto_rawDesc
)

func file_irpc_proto_rawDescGZIP() []byte {
	file_irpc_proto_rawDescOnce.Do(func() {
		file_irpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_irpc_proto_rawDescData)
	})
	return file_irpc_proto_rawDescData
}

var file_irpc_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_irpc_proto_goTypes = []interface{}{
	(*IrpcCallReq)(nil), // 0: irpc.IrpcCallReq
	(*IrpcStatus)(nil),  // 1: irpc.IrpcStatus
	(*Table)(nil),       // 2: irpc.Table
}
var file_irpc_proto_depIdxs = []int32{
	2, // 0: irpc.PushTable.PushTable:input_type -> irpc.Table
	0, // 1: irpc.ExecuterCaller.ExecuterCall:input_type -> irpc.IrpcCallReq
	1, // 2: irpc.PushTable.PushTable:output_type -> irpc.IrpcStatus
	1, // 3: irpc.ExecuterCaller.ExecuterCall:output_type -> irpc.IrpcStatus
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_irpc_proto_init() }
func file_irpc_proto_init() {
	if File_irpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_irpc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IrpcCallReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_irpc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IrpcStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_irpc_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Table); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_irpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_irpc_proto_goTypes,
		DependencyIndexes: file_irpc_proto_depIdxs,
		MessageInfos:      file_irpc_proto_msgTypes,
	}.Build()
	File_irpc_proto = out.File
	file_irpc_proto_rawDesc = nil
	file_irpc_proto_goTypes = nil
	file_irpc_proto_depIdxs = nil
}
